# Server config
[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = KEDyCPT9L/MIdwR9ewpOZOIo4exF8G988mlYqYxepWI=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer_dev_pc
PublicKey = jg5732sGTo7XQvW94Hi6V+P3o4Hxa05deMcaf26aFT0=
PresharedKey = MnAL7lo9ppJeiHPQonjvOHJqzUTqHmf9SLeNnXz/cMQ=
AllowedIPs = 10.13.13.2/32

# Dispositivo 1
[Peer]
PublicKey = pyUujIX4pxf9nOWyboNnNTQxWwUbVW8rzOxxTNPpRCE=
AllowedIPs = 10.13.13.3/32

# Dispositivo 2
[Peer]
PublicKey = xvUaeKT405RTvjsLKf0jHEZqsijm2Url7XWYTSMJJgA=
AllowedIPs = 10.13.13.4/32

# Dispositivo 3
[Peer]
PublicKey = b9VDKAdCAQL2QEIL7WlzRLEUuJjK1ihtEEvLoZxsIFY=
AllowedIPs = 10.13.13.5/32

# Dispositivo 4
[Peer]
PublicKey = B1oDcDqWMUBgNmuFuog+bGIhmiEXUbqclP1hhj3Rchg=
AllowedIPs = 10.13.13.6/32

# Dispositivo 5
[Peer]
PublicKey = f8iYy1uwJfvDtlnHB5nopo08JKxTtAuC/DooLgMatls=
AllowedIPs = 10.13.13.7/32

# Dispositivo 6
[Peer]
PublicKey = mbbFXUwsjQd3VJDW4a/hYfOKLtc4j4kJOGzwx1GKtko=
AllowedIPs = 10.13.13.8/32

# Dispositivo 7
[Peer]
PublicKey = RR/ERoBLNeDTaWIQMvNJkOutgkfpBbWskoOk9TYcowE=
AllowedIPs = 10.13.13.9/32

# Dispositivo 8
[Peer]
PublicKey = qgfSH9MWoSVi1RorCIaEe9ev8WVFoYSh68N3Gto1+EQ=
AllowedIPs = 10.13.13.10/32

# Dispositivo 9
[Peer]
PublicKey = TzhRXQhoJdP/bm85ke+tq8iXnPZSwfatYiBT2PFrRCk=
AllowedIPs = 10.13.13.11/32

# Dispositivo 10
[Peer]
PublicKey = eTadZ9VXhsbQ6ksvS7IMXNfchPaRrXrj7qxNuK0xcRA=
AllowedIPs = 10.13.13.12/32

# Dispositivo 11
[Peer]
PublicKey = FFl8yAR3gnyPwHZEj9BW2Qv+IHaqwCoesalBSVhOzAA=
AllowedIPs = 10.13.13.13/32

# Dispositivo 12
[Peer]
PublicKey = xp4shJffjXf/Tr3qC5sazfyna5m0W3XAyCfDso7PugA=
AllowedIPs = 10.13.13.14/32

# Dispositivo 13
[Peer]
PublicKey = EP++QYNPjxfvaz63khk6+G+hFATfzEtFIZ2HkqvXfyg=
AllowedIPs = 10.13.13.15/32

# Dispositivo 14
[Peer]
PublicKey = 4iDfIPGwkYwWgNiHDAeWuvrCMyX5l1hKhKD6rqZPcns=
AllowedIPs = 10.13.13.16/32

# Dispositivo 15
[Peer]
PublicKey = eFNr/LjlVYhRL3H31kFqb27fUrYxAmhi36ZE/UeUBmU=
AllowedIPs = 10.13.13.17/32

# Dispositivo 16
[Peer]
PublicKey = lquKKGSIrYyt4zeNDdjmQW7r+2F+aVpied5XRSX2Pz8=
AllowedIPs = 10.13.13.18/32

# Dispositivo 17
[Peer]
PublicKey = NL7v2RJPKNiKIvGgjKuc8jhmUjjQkLd7gHoy8PURQ2c=
AllowedIPs = 10.13.13.19/32

# Dispositivo 18
[Peer]
PublicKey = 6GPNdVNXaeDwkXzzQmx440nDDqkq5pKagDUiaINcDD0=
AllowedIPs = 10.13.13.20/32

# Dispositivo 19
[Peer]
PublicKey = aNjdzSlXOsa9Ph/5U+70Iu5Wgxbm5Qf9dkOcUAS+vkg=
AllowedIPs = 10.13.13.21/32

# Dispositivo 20
[Peer]
PublicKey = uKXbTkEis8unehU38oEE63TGqHJjSX/xL3+wtKHH/Aw=
AllowedIPs = 10.13.13.22/32
