# Config for wireguard server on cloud gateway 20 peers added with allowed ips from 10.13.13.2 to 10.13.13.22
# Server config
[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = KEDyCPT9L/MIdwR9ewpOZOIo4exF8G988mlYqYxepWI=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer_dev_pc
PublicKey = jg5732sGTo7XQvW94Hi6V+P3o4Hxa05deMcaf26aFT0=
PresharedKey = MnAL7lo9ppJeiHPQonjvOHJqzUTqHmf9SLeNnXz/cMQ=
AllowedIPs = 10.13.13.2/32

# peer 1
[Peer]
PublicKey = mIlps9TFU5X0tdz76HnlJDR68rIltuDRAOlMUt6KiGE=
AllowedIPs = 10.13.13.3/32

# peer 2
[Peer]
PublicKey = NjxhXzIpRSsVD90KeT9wVofNzDinfTBO0qY+1C/R5lc=
AllowedIPs = 10.13.13.4/32

# peer 3
[Peer]
PublicKey = aChVk/4PufYowKYA4XygMiK2dg8lJvABlHe3ZzNsBWI=
AllowedIPs = 10.13.13.5/32

# peer 4
[Peer]
PublicKey = TFwunCCgn2E8T6rR6PDebh1vSWfXXs/CW+4/WdoI22Y=
AllowedIPs = 10.13.13.6/32

# peer 5
[Peer]
PublicKey = uDiVF7LMWIIGEjflZIMwIW0m65CQ310YUo8nO4LZID0=
AllowedIPs = 10.13.13.7/32

# peer 6
[Peer]
PublicKey = H5d4r660+nAPUbYuLx+Y2sU210DFRR8dTPzrVICNdFA=
AllowedIPs = 10.13.13.8/32

# peer 7
[Peer]
PublicKey = Mee8+aWAM/4SyaiJi2YiKbf9ovy6E2Rz4hOQZBFxy0M=
AllowedIPs = 10.13.13.9/32

# peer 8
[Peer]
PublicKey = WDRJ8YBGJ1L2rolhX+SmaS1x2tp9Xu7Z6jYcN/l4kj0=
AllowedIPs = 10.13.13.10/32

# peer 9
[Peer]
PublicKey = 2slg+ZT0TRYtfyW3oGDqFm/nTiKdESkxJ/wk1uXkJRI=
AllowedIPs = 10.13.13.11/32

# peer 10
[Peer]
PublicKey = O1G8uQJt461CGa14e2BEkK08NlyvznTTfncSvZFoJgM=
AllowedIPs = 10.13.13.12/32

# peer 11
[Peer]
PublicKey = gqIr4Mc9UzRLtxHtfkQLcrs8eXVIHILIwTI1YiGezBI=
AllowedIPs = 10.13.13.13/32

# peer 12
[Peer]
PublicKey = X91DXzORxcS9lpgCXkeLPYnjSrO8jmfZmhKongpAMlw=
AllowedIPs = 10.13.13.14/32

# peer 13
[Peer]
PublicKey = h1VwxbbnssAIScT1xZUerz85vXC0q1qDWPfJpLQi+m0=
AllowedIPs = 10.13.13.15/32

# peer 14
[Peer]
PublicKey = emAQftJNxqkV7aIpnCUoV0yJqlcvEtXdMA5m3v4RsmM=
AllowedIPs = 10.13.13.16/32

# peer 15
[Peer]
PublicKey = nsmuiF+w3MGIY2aHo8L062ajjfHDWI3uDXzWMcXjbT0=
AllowedIPs = 10.13.13.17/32

# peer 16
[Peer]
PublicKey = g8xjIoEJuwK5cW7CpZYZkDc4Y2YdNVk37MzmAiL63Uc=
AllowedIPs = 10.13.13.18/32

# peer 17
[Peer]
PublicKey = Cfiq9sDviBbyOwXkkzhoADYCJhTZcWrZCxPLa6DZAy0=
AllowedIPs = 10.13.13.19/32

# peer 18
[Peer]
PublicKey = h/74rbuUcQ3hteXNGdfs3mC+1NsJ5tm6DxBMzYAAl3k=
AllowedIPs = 10.13.13.20/32

# peer 19
[Peer]
PublicKey = jF2UAVC2CL7uilNkCPrP2o5F4tythvj1ZJNdWNb1SAs=
AllowedIPs = 10.13.13.21/32

# peer 20
[Peer]
PublicKey = S/6e0YAw2mKj+e1KZJEBBwn3dBCyF/l1DR2nDUhenT8=
AllowedIPs = 10.13.13.22/32
