[Interface]
Address = 10.13.13.2
PrivateKey = 8PCt6f+gfPMqOXnBgUUklDioJ/rZqT3HrW4BOJFs1nA=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = QhmCS4QVdZcUxXVVs7RGqnRX6PilGN8E+XCdt1L0Izo=
PresharedKey = MnAL7lo9ppJeiHPQonjvOHJqzUTqHmf9SLeNnXz/cMQ=
Endpoint = 1.0.0.1:51820 ## Ejemplo de IP pública del servidor WireGuard
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25