spring.application.name=Monitoreo Backend

## CONEXION JDBC PROD
## spring.datasource.url=jdbc:postgresql://localhost:5432/monitor_db
## spring.datasource.username=admin

## CONEXION JDBC LOCAL
spring.datasource.url=jdbc:postgresql://db-monitoreo-instance.c5w868iw6fre.us-east-2.rds.amazonaws.com:5432/monitor_db
spring.datasource.username=postgres

spring.datasource.password= postgres123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

server.port=8080
server.address=0.0.0.0